### PR TITLE
chore(ci): use pre-compiled binary on CI

### LINKED ISSUE #2394: Don't compile dependencies on CI
Hi, 👋

Compiling `cross` on CI takes more time compared to pulling the binary directly from a GitHub release.

We can use [taiki-e/install-action](https://github.com/taiki-e/install-action) to pull the binary directly from the GitHub release. This action supports tagging a specific release or using the latest version.

```diff
modified   .github/workflows/ci.yml
@@ -56,9 +56,7 @@ jobs:
-    - name: Install cross
-      # See https://github.com/cross-rs/cross/issues/1222
-      run: cargo install cross --git https://github.com/cross-rs/cross
+    - uses: taiki-e/install-action@cross
```

However, I see that the CI currently pulls from the latest commit with `--git`, which requires compiling.
If you prefer using the latest release, I am ready to make a PR to switch to `taiki-e/install-action`.

Thank you for Iroh 🍜

### PR DESCRIPTION
**Pull request by azzamsa**
## Description

Quoting from #2394 

> Compiling `cross` on CI takes more time compared to pulling the binary directly from a GitHub release.

> We can use [taiki-e/install-action](https://github.com/taiki-e/install-action) to pull the binary directly from the GitHub release. This action supports tagging a specific release or using the latest version.

## Breaking Changes

No.

## Change checklist

- [ ] Self-review.
- [ ] Documentation updates if relevant.
- [ ] Tests if relevant.
- [ ] All breaking changes documented.

Closes #2394

### CODE REVIEW

**Comment by dignifiedquire** [comment]
this doesn’t help us unfortunately as we need to use the concrete code of the usef branch to test agains

**Comment by dignifiedquire** [comment]
oh sorry I misunderstood, this is great, as it installs cross from a prebuilt not our code 😅

**Comment by matheus23** [comment]
Seems like this fails on netbsd and android. Do you know how to fix this @azzamsa?

**Comment by dignifiedquire** [comment]
this is why we used the git dependency, the released version is too old

**Comment by matheus23** [comment]
Seems like the android failure is unrelated to this PR, it's failing on others, too: https://github.com/n0-computer/iroh/actions/runs/9741191219/job/26879873580?pr=2433

**Comment by matheus23** [comment]
Also getting the *other* linker error on another PR now: https://github.com/n0-computer/iroh/actions/runs/9741833183/job/26881854547?pr=2433

**Comment by Arqu** [comment]
Just to give this a bit more color.
- We build directly from git because there was a bug we had with cross that was resolved on main (unsure if there's a release covering it now). Given android builds got moved off this might no longer affect us and we could do this 🤷 
- The latest issues are unrelated to that, though very similar...
- We're moving as much as possible off of cross and just build natively wherever possible

I'll bump the branch and see if the rest of CI passes with it. If so we're ok to merge. I'll leave some commentary.

**Comment by Arqu** [comment]
FWIW I just looked at things, doing it the old fashioned way is faster by 1 sec on average (time it takes for taiki-e/install) vs having it already cached locally :D

I'm still fine with merging, as it uses a stable version and prevents moving targets with cross.

**Review by Arqu — APPROVED** [review]
👍

**Pull request merged**
