### PR TITLE
fix: rename the `README` of `localops/`

### PR DESCRIPTION
**Pull request by amtoine**
hello there :wave: 

#### NOTE: this is about a very minor _GitHub_-rendering-related problem, so i thought opening a preliminary issue was a bit overkill :relieved: 

while browsing you're repo, i've stumbled upon a minor typo in the `iroh-localops/` directory:
- the `README` is called `REAME.md` instead of `README.md`
- it does not render properly as _GitHub_ does not detect it

This PR simply renames `iroh-localops/REAME.md` to `iroh-localops/README.md` :yum:

cheers :tada: 

## checking the work
on current `main`, i.e. 7921050
```bash
> find . -type f -name REAME.md
./iroh-localops/REAME.md
```
and now, i.e. on e1ad44b
```bash
> find . -type f -name REAME.md
# no output
```

### CODE REVIEW

**Review by flub — APPROVED** [review]
Thanks!

**Comment by amtoine** [comment]
> Thanks!
>
glad you like the change :relieved: :wink:

**Comment by flub** [comment]
flaky test being mean.  flaky tests are bad, one day it'll be fixed... one day

**Comment by amtoine** [comment]
> flaky test being mean. flaky tests are bad, one day it'll be fixed... one day
>
i see :yum: 
one day... :relieved:

**Pull request merged**
