### PR TITLE
fix: allow builds without metrics

### PR DESCRIPTION
**Pull request by Arqu**
Closes https://github.com/n0-computer/iroh/issues/149

### CODE REVIEW

**Comment by dignifiedquire** [comment]
hmm, this is a lot of code 😥

**Comment by Arqu** [comment]
> hmm, this is a lot of code 😥

It is, got any better ideas?

My alternative is to make a null metrics implementation and switch on that with features. Might or might not be better but should be more contained.

**Comment by dignifiedquire** [comment]
> My alternative is to make a null metrics implementation and switch on that with features.

I think that might be nicer, I am worried about things like the resolver code having `cfg`s all over the place.

**Comment by Arqu** [comment]
> > My alternative is to make a null metrics implementation and switch on that with features.
> 
> I think that might be nicer, I am worried about things like the resolver code having `cfg`s all over the place.

Yeah it's not pretty. And a bit tedious to annotate every call to every metrics call ever. I'll do another branch for it and see where that goes.

**Pull request closed without merging**
