### PR TITLE
clippy: warn on unsused async fn

### PR DESCRIPTION
**Pull request by dignifiedquire**
Details: https://rust-lang.github.io/rust-clippy/master/index.html#/unused_async

### CODE REVIEW

**Comment by Frando** [comment]
This shouldn't pass, right? E.g. https://github.com/n0-computer/iroh/blob/main/iroh-net/src/magicsock.rs#L2011

**Comment by rklaehn** [comment]
I can not put in words how much I love this lint.

So many times where you have some code that you wish to be sync but you can't do that because it calls some code that is async.

This alone puts the cost/benefit ratio of clippy solidly in the positive despite all my complaints.

**Review by rklaehn — APPROVED** [review]

**Comment by dignifiedquire** [comment]
@rklaehn I added some exceptions in the `iroh-bytes` code, is that the right way, or should I change those functions?

**Comment by rklaehn** [comment]
> @rklaehn I added some exceptions in the `iroh-bytes` code, is that the right way, or should I change those functions?

They are async for 2 reasons:

1. it used to be a trait
2. if we want to lazily load hash seqs, we would need them to be async

So I think they should remain async because of 2. Eventually we will want to lazily load them, but I did not see much urgency since so far we don't have HashSeqs with billions of entries.

**Comment by dignifiedquire** [comment]
will rebase and merge once the current work around magicsock settles down a little bit 😅

**Pull request merged**
