### PR TITLE
test: add large directory roundtrip test

### PR DESCRIPTION
**Pull request by rklaehn**
This was originally intended for the HAMT writing, but uncovered a bug unrelated to HAMTs. At >= 2048 items the stream just hangs. See issue https://github.com/n0-computer/iroh/issues/598

### CODE REVIEW

**Comment by rklaehn** [comment]
@dignifiedquire so you are right, using a multi-threaded executor makes the test work.

But still I really, really, _really_ don't like send_blocking in Drop.

**Comment by dignifiedquire** [comment]
> But still I really, really, _really_ don't like send_blocking in Drop.

I would love alternatives, but we must guarantee the rpc message send on `Drop`, if we don't do that things break down badly.

**Comment by rklaehn** [comment]
> I would love alternatives, but we must guarantee the rpc message send on Drop, if we don't do that things break down badly.

How can you rely on a RPC call for some essential cleanup task? You would think that there would have to be some additional fallback cleanup in case the RPC fails.

**Comment by dignifiedquire** [comment]
> How can you rely on a RPC call for some essential cleanup task? Is there an alternative cleanup mechanism in case the RPC fails?

The more load the system is under, the more important it is to get this message through to clean up as soon as possible. There are timeout based cleanups happening as well, but they are just to a last resort. I ran tests with `try_send` and the system degrades much faster.

**Comment by rklaehn** [comment]
Added this test to #603

**Pull request closed without merging**
