### PR TITLE
try traces

### PR DESCRIPTION
**Pull request by Arqu**
## Description

run 
```
docker run -d -p16686:16686 -p4317:4317 -e COLLECTOR_OTLP_ENABLED=true jaegertracing/all-in-one:latest
```
Open
http://localhost:16686

Run tests.

## Change checklist

- [ ] Self-review.
- [ ] Documentation updates if relevant.
- [ ] Tests if relevant.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
hmm it works, but not super helpful, am I holding it wrong?


Screenshot 2023-10-28 at 15 23 57

**Comment by Arqu** [comment]
Yeah seemed odd to me too. I think we have issues since we spawn separate runtimes also need to instrument more of the stack. Also it depends how much of the time it sees some call to collect samples to surface it.

**Comment by dignifiedquire** [comment]
@Arqu should we try to merge this or close for now?

**Comment by Arqu** [comment]
Close, it's a 20 line commit that doesn't really do what we want for traces.

**Pull request closed without merging**
