### PR TITLE
docs: add docker compose example

### LINKED ISSUE #439: docker mvp
I'd like to add a /docker/ folder with Dockerfile and docker-compose examples

I see in the docs that its mentioned, but don't see any issues.

Is anyone working on this?

If not, any advice and/or encouragement for me?

### PR DESCRIPTION
**Pull request by b5**
and fix env var setting in the process. requires #500

Seeing this work is nice 😄. closes #439

### CODE REVIEW

**Review by Arqu — CHANGES_REQUESTED** [review]
Actually fix tests first 🤣

**Comment by b5** [comment]
@Arqu, hey look at that, the tests caught an issue. It also highlighted an inconsistency that might mess with your life in DevOps land: this PR adjusts `IROH_METRICS` to _also_ use `__` for pathing into compound types, so `IROH_METRICS_FOO` becomes `IROH_METRICS__FOO`.

I think we need to change this to stay consistent. Exceptions remain for `IROH_ENV`, and `IROH_INSTANCE_ID`, which are unchanged by this PR.

**Comment by Arqu** [comment]
> @Arqu, hey look at that, the tests caught an issue. It also highlighted an inconsistency that might mess with your life in DevOps land: this PR adjusts `IROH_METRICS` to _also_ use `__` for pathing into compound types, so `IROH_METRICS_FOO` becomes `IROH_METRICS__FOO`.
> 
> I think we need to change this to stay consistent. Exceptions remain for `IROH_ENV`, and `IROH_INSTANCE_ID`, which are unchanged by this PR.

Good point, feel free to run with this, I'll clean up on my end.

**Review by Arqu — APPROVED** [review]
LGTM if CI passes

**Review by Arqu — APPROVED** [review]
🐹

**Comment by b5** [comment]
cc @Frando, this PR merged your suggested `__` path separator for env vars. Thanks so much for the suggestion!

**Pull request merged**
