### PR TITLE
Add a 'global_only' p2p configuration flag

### PR DESCRIPTION
**Pull request by fabricedesre**
This configures the libp2p transport to not dial addresses in the RFC 1918 range. The code is an adaptation of https://github.com/mxinden/kademlia-exporter/blob/master/src/exporter/client/global_only.rs with changes to replace nightly-only APIs.
With the flag on I've been able to run on a Hetzner box without being flagged for abuse, and to load wikipedia from https://ipfs.capyloon.org/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/English_Wikipedia

Fixes issue n0-computer/beetle#13

### CODE REVIEW

**Comment by flub** [comment]
> The code is an adaptation of https://github.com/mxinden/kademlia-exporter/blob/master/src/exporter/client/global_only.rs 

That repo doesn't seem to have a license associated with it?  So it's hard to know who easily it can be integrated?

**Comment by fabricedesre** [comment]
> > The code is an adaptation of https://github.com/mxinden/kademlia-exporter/blob/master/src/exporter/client/global_only.rs
> 
> That repo doesn't seem to have a license associated with it? So it's hard to know who easily it can be integrated?

Good point. I asked the author in https://github.com/mxinden/kademlia-exporter/issues/243

**Review by dignifiedquire — DISMISSED** [review]
code looks good

**Comment by mxinden** [comment]
> > The code is an adaptation of https://github.com/mxinden/kademlia-exporter/blob/master/src/exporter/client/global_only.rs
> 
> That repo doesn't seem to have a license associated with it? So it's hard to know who easily it can be integrated?

Good catch @flub. I will add a permissive license. In the meantime, as the author of the code, you hereby have my approval to do whatever you like with it, without warranty of course.

**Comment by dignifiedquire** [comment]
@fabricedesre now that we have the OK from @mxinden can you update the code, so we can merge it?

**Comment by fabricedesre** [comment]
> @fabricedesre now that we have the OK from @mxinden can you update the code, so we can merge it?

Done!

**Comment by ramfox** [comment]
Hello! The code that was previously hosted in this repository has been moved to [n0-computer/beetle](https://github.com/n0-computer/beetle). `beetle` is in maintenance mode, but will still accept PRs.

 If you are still interested in getting your PR merged, please re-open your PR on [n0-computer/beetle](https://github.com/n0-computer/beetle).

Check out our blog post for more info on our new direction for `iroh`: https://n0.computer/blog/a-new-direction-for-iroh/

**Pull request closed without merging**
