### PR TITLE
feat(ci): push data to metro

### PR DESCRIPTION
**Pull request by Arqu**

### CODE REVIEW

**Comment by b5** [comment]
Any idea why CI is sad here? I've re run things a few times, encountered flakiness.

**Review by b5 — APPROVED** [review]

**Comment by dignifiedquire** [comment]
> Any idea why CI is sad here? I've re run things a few times, encountered flakiness.

what part of CI is sad? seems all green to me

**Comment by b5** [comment]
I re-ran CI a bunch to make sure it would all turn green. Current commit to `main` shows a similar failure to what I saw: Nix fails, downstream checks go unrun

Screen Shot 2023-02-27 at 10 13 15 AM

**Comment by Arqu** [comment]
Huh, not touching any code here so the *nix builds should be fine. Considering the above Id guess a flake. 
Regarding netsim being red, I bet the CLI interface changed a bit again. Ill have to add a test for people to be aware of breaking changes to netsim.

**Pull request merged**
