### PR TITLE
iroh-rpc-types: Rewrite error handling story

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Part of #491 

This removes `anyhow` from the crate and replaces it with `thiserror`.

There's one TODO left, because there's a `String` somewhere used as error type, which is not nice. But for the first step, this might suffice.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
FWIW, I also have a patch for `iroh-rpc-client`, but as it depends on this PR, I will only file it after this is merged.

**Comment by matthiasbeyer** [comment]
This is obviously not ready yet, but I published it so nobody does double the work... :wink:

**Comment by matthiasbeyer** [comment]
Hah, I begin to see why you said that it won't be that easy... because there's this macro hell in iroh-rpc-types :laughing: 

I will get there though.

**Comment by b5** [comment]
if this ends up being too nighmarish, I'd suggest we leave it. We're actively trying to replace gRPC (and this macro insanity) in the next 4-6 weeks, we might be able to get away with leaving error handling until after such a transition

**Comment by matthiasbeyer** [comment]
Why not the other way round? Get a good error story and then remove the grpc stuff,... this way you end up with the macro nightmare removed _and_ a good interface in terms of error handling! :laughing:

**Comment by b5** [comment]
superseded by #495

**Pull request closed without merging**
