### PR TITLE
ci: Kill tests after 60s using nextest

### PR DESCRIPTION
**Pull request by flub**
## Description

By using nextest to kill slow tests we get logs when a test is killed. This is better than the github timeout kicking in as then we get no feedback on what was stuck.

Tests are now marked as slow after 20s and killed after 60s.

## Notes & open questions

discovery::tests::endpoint_discovery_combined_wrong_only seems like it is a slow tests needing about 30s to complete.  To be fair I think it's fine to call that out as a slow test, so I'm fine with that.

It is possible that this 60s timeout will introduce some new flakyness to the slow CI machines.  We'll have to see and potentially tweak this a bit.

## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

**Comment by Arqu** [comment]
60 seconds might be a bit too tight, some tests in cross can run between 60 and 120s. 
Also the cross tests you want to debug with this are not running with nextest.
Which brings me to another point, we had to specifically block some tests running in parallel before because of interference with each other and nextest allowed us to do this which might be a thing happening now?

**Comment by flub** [comment]
ahahahaha. lol.  cross does not use nextest :sob:

**Comment by Arqu** [comment]
> ahahahaha. lol. cross does not use nextest 😭

Still a great addition, we've talked about this before. No sane single unit test should run >1 min anyways. In general I'd hope <5 sec.

**Comment by dignifiedquire** [comment]
@flub what's the state here?

**Comment by flub** [comment]
Let's merge it, we want this.  and cross will have to be solved separately

**Comment by flub** [comment]
`iroh::provide::sizes` seems to have timed out a few times...

**Comment by flub** [comment]
seems like this might have been triggered by bad staging relays though, not going to investigate more for now

**Pull request merged**
