### PR TITLE
iroh-gateway: Don't send application/octet-stream content-type header

### PR DESCRIPTION
**Pull request by fabricedesre**
This fixes https://github.com/n0-computer/iroh/issues/195

### CODE REVIEW

**Review by dignifiedquire — APPROVED** [review]

**Comment by fabricedesre** [comment]
kubo seems to do content sniffing, since it can tell that QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR content type is image/jpeg

**Comment by Arqu** [comment]
yeah this is correct. octet stream is a carry over from day 1 iroh gw.

**Comment by Arqu** [comment]
Created https://github.com/n0-computer/iroh/issues/197 as a follow up.

**Comment by Arqu** [comment]
Also thanks! :)

**Pull request merged**
