### PR TITLE
experiment: try to only use tokio::mpsc in iroh-net

### PR DESCRIPTION
**Pull request by dignifiedquire**
I am failing to implement the `send_blocking`, if anyone has ideas, I would love to hear them

### CODE REVIEW

**Comment by rklaehn** [comment]
Pushed a fix. But this isn't really send_blocking, more like send_blocking without runtime and send_detached or whatever in case a runtime is found.

It might be that this is OK in most cases. But then the fn should be called send_sync or something and return just unit to signal that it is fire and forget / best effort.

**Comment by rklaehn** [comment]
As you mention, the calls to send_blocking can be replaced by a normal send call just by making some fns async. So should we just do that?

send_blocking works now, except that it is not really blocking in the case where a runtime is found. But we don't need it at all in iroh-net.

**Comment by dignifiedquire** [comment]
> As you mention, the calls to send_blocking can be replaced by a normal send call just by making some fns async. So should we just do that?

yes, we should try and do that

**Comment by dignifiedquire** [comment]
closing in favor of #2620

**Pull request closed without merging**
