### PR TITLE
[feat] HEAD for CIDs + refactoring of handlers

### PR DESCRIPTION
**Pull request by ppodolsky**
Here I've done several things:
- Added HEAD handler that returns `Content-Length` header as in Kubo
- Refactored handlers to make them slightly more idiomatic
- Fixed [bug](https://github.com/n0-computer/iroh/blob/main/iroh-gateway/src/response.rs#L144) that doesn't set Location in redirect
- Applied Clippy to iroh-gateway

### CODE REVIEW

**Comment by fabricedesre** [comment]
It would be really nice to add tests for the `HEAD` requests.

**Comment by ppodolsky** [comment]
Done!

**Comment by ppodolsky** [comment]
@Arqu Did you reconfigure clippy recently? Checks are failing on code that I didn't write. I can fix it anyway.

**Comment by Arqu** [comment]
Can you rebase, shouldn't be the case.

**Comment by ppodolsky** [comment]
Rebase again, all checks was ok @Arqu

**Comment by Arqu** [comment]
> Rebased again, all checks was ok @Arqu

Sorry, lots of stufff floating around. Reviewing now.

**Review by Arqu — APPROVED** [review]
Regret not merging earlier, thank you for the big sweepin cleanup.

**Pull request merged**
