### PR TITLE
feat(gateway): Add about page

### PR DESCRIPTION
**Pull request by flub**
Add an about page with a bit of package information.

---

I just found this useful locally as I learn how things work.  Maybe
others like it too.  If not, never mind.

### CODE REVIEW

**Review by Arqu — CHANGES_REQUESTED** [review]
I would be fine with including this. However a common convetion for this is to use `z` routes. Like `/healthz` we can move this from an `about` page into an `infoz` and we can add more info later to it. 
I assume anybody hosting this as a gateway would either want to turn it off or customize the about page.

**Comment by b5** [comment]
the `z` suffix is a google-ism that means "this route should not be publicly accessible". Let's _not_ use `z` suffixes unless we mean to enforce that rule (and we really can't, so let's just not use 'em). I'd vote for just `/info`.

**Comment by Arqu** [comment]
> the `z` suffix is a google-ism that means "this route should not be publicly accessible". Let's _not_ use `z` suffixes unless we mean to enforce that rule (and we really can't, so let's just not use 'em). I'd vote for just `/info`.

Agree, I'm fine with just info but also it being a non-public route should be fine and is also probably expected for 3rd party users if the host it as a service.

**Comment by dignifiedquire** [comment]
why not `/about` ?

**Comment by Arqu** [comment]
> why not `/about` ? 

I don't think I've seen many/any about pages with this kind of info. 
Also people potentially hosting the gw would definitely prefer a different about.

**Comment by flub** [comment]
I'm happy to settle on `/info`.  I also added git revision, PTAL.

**Review by Arqu — APPROVED** [review]
👍

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
