### PR TITLE
feat: use chunk groups feature

### PR DESCRIPTION
**Pull request by rklaehn**
caution: this is not compatible with existing iroh/sendme

### CODE REVIEW

**Comment by dignifiedquire** [comment]
what's missing here, given this is a draft?

**Comment by rklaehn** [comment]
It was a draft because the crate was not published yet, and the tests were failing. Let's see, maybe they work now...

**Comment by dignifiedquire** [comment]
@rklaehn do we want to ship this? did you compare the perf numbers?

**Comment by rklaehn** [comment]
Well, perf is basically identical, a tad faster. The main benefit is that the outboard is smaller, so we can share larger files with outboard in memory.

As far as I am concerned it is ready to go - provided that we're clear that this might change in the future, together with the protocol.

**Comment by dignifiedquire** [comment]
@flub any concerns merging this before DC release?

**Review by flub — APPROVED** [review]

**Pull request merged**
