### PR TITLE
fix(net): correct packet math for poll_recv

### PR DESCRIPTION
**Pull request by dignifiedquire**
## Description

- `meta.len` is the length of the actually received data (not `buf.len()`)
- `meta.stride` is the length of an individual packet (not `meta.len`)

This was triggering https://github.com/n0-computer/iroh/issues/1696 because for STUN packets the additional (empty) buffer was considered to be QUIC packets, resulting in the warning.

### CODE REVIEW

**Review by Frando — APPROVED** [review]
Great find!

**Comment by divagant-martian** [comment]
I have no idea if it's hard to mock or not, but would it make sense to test that stun packages are correctly received on this end? If we were reporting stun packages as udp ones then stun ones were failing and CI didn't notice

**Comment by dignifiedquire** [comment]
the stun packets were correctly reported, there were just additional packets reported, which is why tests didn’t pick this up

**Pull request merged**
