### PR TITLE
refactor(iroh): remove the addr arg from start

### PR DESCRIPTION
**Pull request by divagant-martian**
## Description

Removes the add from the start args as discussed internally. Reason for this is that it's currently not used. In reality, the port was not used. If we do add this back, most likely we want to also use the address to allow ipv6 listening nodes. In the spirit of removing code we opt for letting the code reflect how it's actually used in the moment

## Notes & open questions

na

## Change checklist

- [ ] Self-review.
- [ ] Documentation updates if relevant.
- [ ] Tests if relevant.

### CODE REVIEW

**Comment by Arqu** [comment]
This is the custom run: https://github.com/n0-computer/iroh/actions/runs/6974445664/job/18980130821
If it passes we should merge https://github.com/n0-computer/chuck/pull/47 and then this PR

**Comment by Arqu** [comment]
Can you rebase on top of https://github.com/n0-computer/iroh/pull/1834?

**Comment by divagant-martian** [comment]
rebased @Arqu but netsim is still unhappy

**Comment by Arqu** [comment]
Ugh so a couple clarifications:
- the CI PR I did doesn't work for summoning netsim-CI till it's merged into main
- I merged that and we need to rebase this from main
- Once rebased the CI will still be red on the PR but then we can check against the netsim tests with `/netsim branch arqu/drop_addr` 
- If all is good we merge the netsim PR and then your PR


- To make life easier I'll check manually we can merge my PR and then your PR and be done with it, but I just want to test that the "invoke netsim from a fork" workflow works.

**Comment by Arqu** [comment]
Can confirm it works in a manual test with netsim. Will just wait it out to test the comment based CI to see if it works. Can then proceed to merge stuff.

**Review by Arqu — APPROVED** [review]

**Pull request merged**
