### PR TITLE
[WIP] feat: compress blobs on transfer

### LINKED ISSUE #739: Use lz4 compression
When sending files that are not already somehow encoded, there would be a large gain 

There is a fully rust compression library called lz4_flex. https://crates.io/crates/lz4_flex

We could use this to reduce the amount of data that needs to be sent through en/decryption and through quic. Even for uncompressible data lz4 is very fast, so you probably would not even notice it WRT perf compared to the quic overhead.

The downside is the additional complexity. We should try this out only after having implemented/used larger bao block size. See n0-computer/iroh#741

Edit: zstd provides much better compression rates but is much more expensive. Also, there is no pure rust impl of zstd, unfortunately...

### PR DESCRIPTION
**Pull request by dignifiedquire**
Currently broken, likely due to a bug somewhere in the asnycread/write impls of async-compression or abao

Closes #739

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Looks like our usage is simply not possible currently: https://github.com/Nemo157/async-compression/issues/141

**Comment by flub** [comment]
you could write a custom inner writer that doesn't pass through the closing...

**Comment by rklaehn** [comment]
Can somebody enlighten me why we want to compress individual files instead of the entire stream?

**Comment by rklaehn** [comment]
If we do this we should do the version where the entire request is compressed as one, seee #864

**Comment by dignifiedquire** [comment]
meh, closing this one

**Pull request closed without merging**
