### PR TITLE
Add some metrics counters to the doctor

### PR DESCRIPTION
**Pull request by rklaehn**
Add some metrics to the doctor

Which ones would you find most useful, @ramfox or @dignifiedquire ?

I would make a nice console gui for them then. I guess group by send and recv?

image

### CODE REVIEW

**Comment by dignifiedquire** [comment]
something like
```
Derp:
  send: 54 MiB
  recv: 54 MiB
Ipv4:
  send: 54 MiB
  recv: 54 MiB
Ipv6:
  send: 54 MiB
  recv: 54 MiB
```

**Comment by dignifiedquire** [comment]
fyi quinn also has stats, which would be interesting to show

**Comment by rklaehn** [comment]
I will make a nice panel. What you want to see probably depends on the specific scenario, so I doubt that you can come up with something perfect here.

But you should be able to clearly see the derp -> udp switchover etc.

**Review by dignifiedquire — APPROVED** [review]

**Comment by dignifiedquire** [comment]
looks like some compile errors

**Comment by rklaehn** [comment]
should be fixed now. Also did clippy.

**Pull request merged**
