### PR TITLE
refactor(iroh-net): Improve magicsock module visibility

### PR DESCRIPTION
**Pull request by flub**
## Description

This audits the public visibility of items in the magicsock module. pub(super) and pub(crate) mean the same thing here, since it is a top-level module.  This prefers pub(crate) to make it clear who can see the items.  Likewise it marks sub-items pub(crate) as well to make the visibility clear.

## Notes & open questions

This is targetted at #2369 which will need to be merged first.

## Change checklist

- [x] Self-review.
- ~~[ ] Documentation updates if relevant.~~
- ~~[ ] Tests if relevant.~~
- [x] All breaking changes documented.

### CODE REVIEW

**Comment by divagant-martian** [comment]
Related https://github.com/n0-computer/iroh/pull/1895/files

**Comment by flub** [comment]
> Related https://github.com/n0-computer/iroh/pull/1895/files

huh, good catch.  I re-added it.  How come the compiler does not complain about this?

**Review by divagant-martian — APPROVED** [review]
LGTM. I updated the PR tittle and description to remove the breaking change. I'm honestly not sure why the compiler is not complaining, or at least I can't remember right now. We should probably check what's going on, but for the scope of the PR that's not an issue

**Comment by divagant-martian** [comment]
Since you did not mention a base PR, I'm assuming this was meant to be `main`. I'll hold on merging so that you can decide whether we need to re-review the whole changes or if this was indeed on top of another branch, etc.

**Comment by flub** [comment]
> Since you did not mention a base PR, I'm assuming this was meant to be `main`. I'll hold on merging so that you can decide whether we need to re-review the whole changes or if this was indeed on top of another branch, etc.

The notes section did mention it was on top of the other PR.  Setting it to bade directly means it'll include the commits of the other branch as well.  Leaving it to that branch means it will automatically rebase on any other commits added to the base branch.  I chose this because I suspected doing the two PRs independently would give merge conflicts in one of them, so thought it was easier to sequence them.  admittedly github could improve that workflow

**Pull request merged**
