### PR TITLE
fix(iroh-one): Wire up mem addresses to each other

### PR DESCRIPTION
**Pull request by flub**
This copies the mem-addresses in the config to the bits of config that
are used by the individual services before starting them up.  This
should help them talk to each other a little better.

---

Tested this locally and seems to work, I think?

### CODE REVIEW

**Comment by dignifiedquire** [comment]
> Tested this locally and seems to work, I think?

What did you test? 

This might be one of the reasons for https://github.com/n0-computer/iroh/issues/542 because bitswap/p2p can't provide anything if it is not connected to the store.

**Comment by flub** [comment]
I tried a simple get via the http interface after clearing all local state

**Comment by dignifiedquire** [comment]
did you check if the content got stored? resolving content only requires the gateway to be connected to the store, not p2p

**Comment by fabricedesre** [comment]
> > Tested this locally and seems to work, I think?
> 
> What did you test?
> 
> This might be one of the reasons for #542 because bitswap/p2p can't provide anything if it is not connected to the store.

You're spot on! I tried this branch on top of my http-put one and things work as expected! Woohoo!

**Review by dignifiedquire — APPROVED** [review]

**Comment by flub** [comment]
> resolving content only requires the gateway to be connected to the store, not p2p

If the store was deleted first I assumed it needs to come back from the p2p node first to make it into the store?  So having deleted the store I'd be more concerned about whether the p2p node can fetch things and serve it without it making it into the store.  Is that possible or will it always go via the store?

**Comment by dignifiedquire** [comment]
@flub I don’t get it 😅 But merging given @fabricedesre confirmation it fixes a bug for him. 

We should note that we get a test for this..

**Comment by flub** [comment]
> We should note that we get a test for this..

yes, I thought that as well.  I think this should be a lot more doable once we have the e2e story progressed a bit more.

**Pull request merged**
