### PR TITLE
ref: Move packet building into conn

### PR DESCRIPTION
**Pull request by rklaehn**
As suggested by @ramfox in https://github.com/n0-computer/iroh/pull/830#discussion_r1191830689

This undoes a lot of the changes to tests that were done in the initial batching PR. The packetize and packet split iter moved to the conn.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
I am not seeing any place where the packets are split on receiving, did you miss that piece?

**Comment by rklaehn** [comment]
> I am not seeing any place where the packets are split on receiving, did you miss that piece?

I did not change anything about this. It is in process_derp_read_result. The only remaining place where PacketSplitIter is still used.

**Comment by dignifiedquire** [comment]
ahh, right :)

**Comment by dignifiedquire** [comment]
did you test performance? I assume no change?

**Comment by rklaehn** [comment]
> did you test performance? I assume no change?

I did not test perf. It does the same thing, just in a different place. Same number of allocations etc.

Although to be fair I think we are not at the point where we have to worry about allocations. Hopefully we will get there eventually...

**Pull request merged**
