### PR TITLE
refactor(iroh)!: remove tags from downloader

### PR DESCRIPTION
**Pull request by rklaehn**
## Description

Remove tags from downloader. Adding temp or persistent tags is now the responsibility of the caller.

## Breaking Changes

- iroh_blobs::downloader::DownloadRequest
    - field `tag` is removed
    - fn `untagged` is removed
    - fn `tag` is removed

Docs are changed to indicate that tagging is now responibility of the caller...

## Change checklist

- [x] Self-review.
- [x] Documentation updates if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
definitely looks like a nice simplification, but @Frando will have to answer if this is missing something crucial

**Comment by Frando** [comment]
Aha, interesting. I somehow did not realize that we can create tags before we have the data, I thought only temptags could do that. So I think this is fine. We should document this somewhere on the downloader though (it's public API) that users need to create tags themselves otherwise their newly downloaded blobs will be garbage collected at any time.

**Comment by Frando** [comment]
One advantage of having it in the downloader is that if queuing the same downloader multiple times from the client API with SetTagOption::Auto you used to have only one auto tag, and now you'd have 2.

**Comment by rklaehn** [comment]
> One advantage of having it in the downloader is that if queuing the same downloader multiple times from the client API with SetTagOption::Auto you used to have only one auto tag, and now you'd get multiple auto tag. I think this was the original reason I moved the tagging into the downloader and added the TagSet.

Not sure that warrants the additional complexity. also, handing the same auto tag to 2 places is a bit dangerous, given that I think currently we are using auto tags as a workaround for the fact that temp tags are not available on the rpc client.

E.g. you got one place that does download with auto, then some validation, then removes the auto tag and replaces it with something permanent/named. The other side will not notice this, so they will have an auto tag that is not actually tagging anything anymore.

In general I think most uses for SetTagOption::Auto will be replaced by temp tags once we have them in the rpc client.

**Comment by dignifiedquire** [comment]
please document the breaking changes

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
