### PR TITLE
refactor(iroh-net)!: Rename AddrInfo to NetworkPaths

### PR DESCRIPTION
**Pull request by flub**
## Description

This was already the leading summary of the doc comment.

## Breaking Changes

- `AddrInfo` has been renamed `NetworkPaths`.
- `NodeAddr::info` has been renamed `NodeAddr::paths`.
- `AddrInfoOptions` has been renamed `NodeAddrOptions`.
- `AddrInfo::apply_options` has been removed.

## Notes & open questions

This comes from a larger refactor that was trying to remove AddrInfo
from the public API after it was observed it was only used in
discovery.  However replacing it there with it's contituent parts was
not popular with everyone, and introducing a struct just in discovery
leads to a lot of churn with nothing really being achieved.

If this stays as a struct for discovery and internal use anyway, it
might as well still be used in NodeAddr I guess.  Renaming it should
solve the confusion of what the difference between NodeAddr and
AddrInfo is as well.

Honestly, I don't know if this is still useful.  But it's basically a
PR entirely written by rust-analyzer so I might as well create it.  But
this does seem a bit pointless to be churning at right at this time.
I was expecting this to be simpler and more obvious.

## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
> `NodeAddr` has been renmaed `NetworkPaths`.

I belive it is `AddrInfo`?

**Comment by flub** [comment]
> > `NodeAddr` has been renmaed `NetworkPaths`.
> 
> I belive it is `AddrInfo`?

Yep, that was a typo.  Just updated the description with things being a bit more complete now, I missed a few things on the first pass.

**Comment by dignifiedquire** [comment]
why you close this?

**Comment by flub** [comment]
ugh, out of frustration for wasting time on this :(

Because I'm no long sure how useful this is and it was triggering tons of CI failures that look related to all the moving of crates.  It just seemed too much of a pain to get something so low value in while we're doing much more important things that could do with settling.

**Pull request closed without merging**
