### PR TITLE
feat(iroh): make all important iroh_base types available

### PR DESCRIPTION
**Pull request by dignifiedquire**
## Description

Otherwise one has to pull in some things from `iroh-base` and some from here

## Breaking Changes

None, just additions

## Change checklist

- [ ] Self-review.
- [ ] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [ ] Tests if relevant.
- [ ] All breaking changes documented.

### CODE REVIEW

**Review by matheus23 — APPROVED** [review]
Well so this adds `iroh::hash` and `iroh::AddrInfoOptions` (also available under `endpoint`).

The only other thing in `iroh_base` that is not yet exported is `iroh_base::base32`.

**Review by rklaehn — APPROVED** [review]
I assume that this does not mean that things like AddrInfoOptions will remain until 1.0. Personally I think it is not that useful.

**Comment by dignifiedquire** [comment]
> I assume that this does not mean that things like AddrInfoOptions

it is actively used right now in code, which is why I need to expose it, but would love to see a PR improving the API

**Comment by dignifiedquire** [comment]
> will remain until 1.0.

`iroh-base` is part of hitting `1.0`, so time to clean up any APIs you don't think should stay

**Pull request merged**
