### PR TITLE
[test] Empty PR for testing netsim

### PR DESCRIPTION
**Pull request by matheus23**
## Change checklist

- [ ] Self-review.
- [ ] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [ ] Tests if relevant.
- [ ] All breaking changes documented.

### CODE REVIEW

**Comment by matheus23** [comment]
Tried testing iroh with netsim configured to 5s latency, in order to test use cases like #2337
Logs are here: https://github.com/n0-computer/iroh/actions/runs/11122485757/artifacts/1999863925

Seems like it ran through fine.
The throughput was still set fairly high (1gbps), which would be unrealistic for a mobile network on a train, and 2% packet loss may or may not be super accurate, but shouldn't be *too* far off.

**Comment by Arqu** [comment]
Seems like double NAT + relay works fine too https://github.com/n0-computer/iroh/actions/runs/11122850370

**Comment by matheus23** [comment]
Judging from the throughput numbers, in the NAT case, did it perhaps only use the relay?

**Comment by Arqu** [comment]
No, it seems fine, just that test used a 1MB transfer which doesn't leave much time for it to ramp up the throughput and is mostly time dominated by the setup of the connection.

**Pull request closed without merging**
